### ISSUE TITLE
Edit documentation

### ISSUE THREAD

**Issue by ljl7123** [fadedDexofan/koa-typeorm-boilerplate#2]
My university technical writing course has an assignment which involves editing documentation on GitHub repositories as practice in real world settings. Edits may involve aspects like style, structure, and concision. Existing style guidelines would be taken into account. The following is one of the resources I would be using:

https://jacobian.org/writing/technical-style/

Would anyone mind if I add or propose edits to documentation in this repository? It would really help me out!

**Comment by fadedDexofan** [comment]
I think starter project doesn't need documentation. Try search some libs without documentation.
